cf_elbo_type: -1
data_dir: /Users/ahmedabdulaal/Documents/DSCM_debug/deepscm/assets/data/morphomnist
decoder_cov_rank: 10
decoder_type: fixed_var
experiment: SVIExperiment
hidden_dim: 100
l2: 0.0
latent_dim: 16
logstd_init: -5
lr: 0.0001
model: ConditionalVISEM
num_sample_particles: 32
num_svi_particles: 4
pgm_lr: 0.005
preprocessing: realnvp
sample_img_interval: 10
test_batch_size: 256
train_batch_size: 256
use_amsgrad: false
use_cf_guide: false
validate: false
